### ISSUE TITLE
On build startup

### ISSUE THREAD

**Issue by GrmpyPmpkin** [derek-fong/angular2-meteor-boilerplate#3]
While checking for angular2-compilers@0.6.1:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

Please advise ?

**Comment by GrmpyPmpkin** [comment]
I seem to have fixed it by `meteor add angular2-compilers@=0.6.0`

Thanks

**Comment by derek-fong** [comment]
Are you running this app on Windows platform?

According to https://github.com/Urigo/angular2-meteor/issues/372 users have reported with same issues on Windows platform and the workaround is to `use angular2-compilers@=0.6.0` by executing `meteor add angular2-compilers@=0.6.0` until `angular2-meteor` team has resolve this problem. 

Also, if you are using `angular2-compilers@=0.6.0` you may also need to `meteor add barbatus:typescript` to the latest version (currently 0.4.0) to avoid those `cannot find module` errors. Latest `angular2-compilers` package has `barbatus:typescript@0.4.0` included which is based on Typescript 2.0 while `angular2-compilers@=0.6.0` is using a previous version of `barbatus:typescript` (See: https://github.com/barbatus/typescript).

**Comment by GrmpyPmpkin** [comment]
Yep, I am using windows... :|

It works perfectly now :), thank you.

**Comment by mahesh0431** [comment]
@derek-fong hi, i am cloned the boiler plate https://github.com/bsliran/angular2-meteor-base socially and installed the same and when i am running it by using meteor command, i am facing the same issue. So i tried to install the 0.6 compiler by using **meteor add angular2-compilers@=0.6.0** but when i did, i got this error:

C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.flush (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:70:8)
    at BlockStream.end (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:66:8)
    at Extract.Parse.end (C:\Users\GSS\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:86:23)
    at Gunzip.onend (_stream_readable.js:498:10)
    at Gunzip.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Gunzip.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

Again like you said, i tried to install the older typings by using **meteor add barbatus:typescript**  then again i got the same error: 
While checking for angular2-compilers@0.6.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.

dont know what to do, someone please help..

p.s: i am new to meteor & node

Best Regards,
Mahesh

**Comment by derek-fong** [comment]
@mahesh0431 I suspect you have forgotten to install the NPM packages?

Here are the there steps I have performed to get the app running on Windows platforms: 

```
meteor add angular2-compilers@=0.6.0  // Windows platforms workaround as mentioned above
meteor add barbatus:typescript@=0.4.0 // You won't need to explicitly include this in future `angular2-compilers` version
meteor npm install  // Install NPM packages
meteor  // Run the app
```

Have fun :)

**Comment by mahesh0431** [comment]
Hi @derek-fong , Thanks its working now, actually i installed it first and i got errors and then i tried to follow your steps, it didnt worked. Now i git cloned the boilerplate and then tried your steps, it worked now.
Now i got one more issue, the typings installation failed. So i tried to do that step manually as per the angular 2 quick install tutorial, but i am getting the below error:

> npm run typings install
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "typings" "install"
> npm ERR! node v5.4.1
> npm ERR! npm  v3.3.12

npm ERR! missing script: typings
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GSS\Desktop\Me\Web Development\meteor\socially\npm-debug.log

Could you please help me on this

Best Regards,
Mahesh

*_Update, issue is solved: I need to add the typings script in the package.json, now its working, Thanks for helping @derek-fong *_

**Comment by derek-fong** [comment]
@mahesh0431 

You attempted to execute a command which NPM does not understand: 

> `npm run typings install`

My suggestion is to modify your project's `package.json` with the correct scripts, or try to install `typings` by following [this](https://github.com/Urigo/angular2-meteor#typings) documentation:  

```
npm install typings -g  // Install `typings` package globally
typings install registry:env/meteor --global  // Install `meteor` typings

```

**Comment by mahesh0431** [comment]
Thanks @derek-fong  it's working now..

**Comment by mahesh0431** [comment]
@derek-fong , Hi derek, i got another issue which is not related to your git repo,  actually i am trying to follow a angular2 meteor tutorial, which has the boilerplate ref to the another git repo. I have raised an issue there. I thought u know angular2 meteor a lot, so just informing you in case if you are aware of this this issue: https://github.com/bsliran/angular2-meteor-base/issues/36. 

Thanks!!

Best Regards,
Mahesh

**Comment by derek-fong** [comment]
@mahesh0431 See https://github.com/Urigo/angular2-meteor/issues/401

```
meteor add barbatus:angular2-polyfills
```

Maybe you should consider opening a separate issue next time as your questions posted here are no longer related to OP's original issue.

**Comment by mahesh0431** [comment]
@derek-fong , yeah derek, i have opened a new issue, but dont know how mention you there, so i commented here :(

**Comment by derek-fong** [comment]
@mahesh0431 all good I am happy to help but just don't want to confuse other people.

**Comment by derek-fong** [comment]
@danielleburgess @mahesh0431 

FYI https://github.com/Urigo/angular2-meteor/issues/410

New `angular2-compilers` should resolve your issue.
